#!/usr/bin/env python3
"""
EVEZ Hypothesis Engine — 6-hour.
Reads COGNITION_REPORTs + spectral data + issue trends.
Generates 3 falsifiable hypotheses about what to build next.
Opens GitHub issues tagged [HYPOTHESIS] for human review.
"""
import os, json, datetime, hashlib, requests, base64

GH_TOKEN = os.environ.get("GITHUB_TOKEN", "")
ANTHROPIC_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
ABLY_KEY = os.environ.get("ABLY_KEY", "")
OWNER = "EvezArt"

HEADERS = {
    "Authorization": f"Bearer {GH_TOKEN}",
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
}

TARGET_REPOS = ["evez-autonomous-ledger", "evez-agentnet", "Evez666"]


def now_iso():
    return datetime.datetime.utcnow().isoformat() + "Z"


def get_cognition_reports(limit=5):
    try:
        url = f"https://api.github.com/repos/{OWNER}/evez-autonomous-ledger/contents/DECISIONS"
        r = requests.get(url, headers=HEADERS, timeout=15)
        if r.status_code != 200:
            return []
        files = [f for f in r.json() if "COGNITION_REPORT" in f["name"]]
        files = sorted(files, key=lambda x: x["name"], reverse=True)[:limit]
        reports = []
        for f in files:
            fr = requests.get(f["url"], headers=HEADERS, timeout=15)
            if fr.status_code == 200:
                try:
                    reports.append(json.loads(base64.b64decode(fr.json()["content"]).decode()))
                except Exception:
                    pass
        return reports
    except Exception as e:
        print(f"  ⚠️  get_cognition_reports failed: {e}")
        return []


def call_claude(prompt):
    if not ANTHROPIC_KEY:
        return None
    import urllib.request
    body = json.dumps({
        "model": "claude-3-haiku-20240307",
        "max_tokens": 1200,
        "messages": [{"role": "user", "content": prompt}]
    }).encode()
    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=body,
        headers={
            "x-api-key": ANTHROPIC_KEY,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        }
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            return json.loads(resp.read())["content"][0]["text"]
    except Exception as e:
        print(f"  ⚠️  call_claude failed: {e}")
        return None


def generate_hypotheses(reports):
    syntheses = "\n\n".join([r.get("synthesis", "")[:300] for r in reports])
    prompt = f"""You are the EVEZ hypothesis engine for an autonomous AI development system.

Recent cognition reports:
{syntheses}

Generate exactly 3 hypotheses. Each must be:
- Falsifiable (testable by running code or observing metrics)
- Actionable (leads to a specific implementation)
- Numbered H1, H2, H3

Format each as:
H[N]: [HYPOTHESIS TITLE]
PREDICTION: [what should happen if true]
TEST: [how to verify in code/metrics]
IMPACT: HIGH/MEDIUM/LOW
TARGET_REPO: [which evez repo to implement in]"""
    return call_claude(prompt)


def parse_hypotheses(text):
    if not text:
        return []
    hypotheses = []
    for n in ["H1", "H2", "H3"]:
        start = text.find(f"{n}:")
        if start == -1:
            continue
        end = text.find(f"H{int(n[1:])+1}:", start) if n != "H3" else len(text)
        block = text[start:end].strip()
        lines = block.split("\n")
        title = lines[0].replace(f"{n}:", "").strip()
        hypotheses.append({"id": n, "title": title, "block": block})
    return hypotheses


def open_hypothesis_issue(repo, hypothesis):
    try:
        url = f"https://api.github.com/repos/{OWNER}/{repo}/issues"
        body = f"{hypothesis['block']}\n\n*🔮 Auto-generated by hypothesis_engine.py | Requires human review before any action.*"
        r = requests.post(url, headers=HEADERS, json={
            "title": f"🔮 [HYPOTHESIS] {hypothesis['title']}",
            "body": body,
            "labels": ["hypothesis", "autonomous-cognition"],
        }, timeout=15)
        return r.status_code in (200, 201)
    except Exception as e:
        print(f"  ⚠️  open_hypothesis_issue failed: {e}")
        return False


def main():
    try:
        print(f"\n🔮 EVEZ Hypothesis Engine — {now_iso()}")
        reports = get_cognition_reports()
        print(f"  Loaded {len(reports)} cognition reports")

        hypothesis_text = generate_hypotheses(reports)
        if not hypothesis_text:
            print("  ⚠️  No API key — skipping hypothesis generation")
            return

        hypotheses = parse_hypotheses(hypothesis_text)
        print(f"  Generated {len(hypotheses)} hypotheses")

        for i, h in enumerate(hypotheses):
            repo = TARGET_REPOS[i % len(TARGET_REPOS)]
            opened = open_hypothesis_issue(repo, h)
            print(f"  {'✅' if opened else '❌'} {h['id']}: {h['title'][:60]} → {repo}")

        # Write to ledger
        record = {
            "type": "hypothesis_batch",
            "source": "cognition/hypothesis_engine",
            "timestamp": now_iso(),
            "hypotheses": hypotheses,
            "hash": hashlib.sha256(hypothesis_text.encode()).hexdigest()[:16],
        }
        content = base64.b64encode(json.dumps(record, indent=2).encode()).decode()
        ts = now_iso().replace(":", "-").replace(".", "-")
        try:
            requests.put(
                f"https://api.github.com/repos/{OWNER}/evez-autonomous-ledger/contents/DECISIONS/{ts}_hypotheses.json",
                headers=HEADERS,
                json={"message": f"🔮 hypotheses batch @ {record['timestamp']}", "content": content},
                timeout=15,
            )
        except Exception as e:
            print(f"  ⚠️  Ledger write failed: {e}")
        print("  ✅ Hypothesis batch complete.")
    except Exception as e:
        print(f"  ⚠️  main() failed: {e}")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"hypothesis_engine fatal error: {e}")
        exit(0)
