#!/usr/bin/env python3
"""
EVEZ Evolution Engine — 12-hour.
Reads MEMORY_STATE.json + recent COGNITION_REPORTs.
Determines if the system should:
  1. Spawn a new agent (new .py file proposal)
  2. Retire/merge a redundant agent
  3. Upgrade a workflow cadence
  4. Open a new data source for sensing
All proposals are GitHub Issues — nothing auto-merges.
"""
import os, json, datetime, hashlib, requests, base64

GH_TOKEN = os.environ.get("GITHUB_TOKEN", "")
ANTHROPIC_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
ABLY_KEY = os.environ.get("ABLY_KEY", "")
OWNER = "EvezArt"

HEADERS = {
    "Authorization": f"Bearer {GH_TOKEN}",
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
}


def now_iso():
    return datetime.datetime.utcnow().isoformat() + "Z"


def get_memory_state():
    try:
        url = f"https://api.github.com/repos/{OWNER}/evez-autonomous-ledger/contents/MEMORY_STATE.json"
        r = requests.get(url, headers=HEADERS, timeout=15)
        if r.status_code == 200:
            return json.loads(base64.b64decode(r.json()["content"]).decode())
        return {}
    except Exception as e:
        print(f"  ⚠️  get_memory_state failed: {e}")
        return {}


def call_claude(prompt):
    if not ANTHROPIC_KEY:
        return None
    import urllib.request
    body = json.dumps({
        "model": "claude-3-haiku-20240307",
        "max_tokens": 1500,
        "messages": [{"role": "user", "content": prompt}]
    }).encode()
    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=body,
        headers={
            "x-api-key": ANTHROPIC_KEY,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        }
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            return json.loads(resp.read())["content"][0]["text"]
    except Exception as e:
        print(f"  ⚠️  call_claude failed: {e}")
        return None


def generate_evolution_plan(memory):
    top_keywords = list(memory.get("top_web_keywords", {}).keys())[:10]
    event_dist = memory.get("event_type_distribution", {})
    failures = memory.get("recurring_failure_modes", [])
    lessons = memory.get("lessons_count", 0)

    prompt = f"""You are the EVEZ evolution engine. You decide how an autonomous AI agent network should evolve.

Current memory state:
- Total records processed: {memory.get('total_records', 0)}
- Event distribution: {json.dumps(event_dist)}
- Top sensory keywords: {top_keywords}
- Recurring failures: {failures}
- Lessons accumulated: {lessons}

Currently running agents:
- web_sense.py (30-min RSS/arXiv/HN perception)
- github_sense.py (20-min repo health)
- synthesizer.py (1-hour cognition)
- hypothesis_engine.py (6-hour proposals)
- consolidator.py (3-hour memory)
- self_repair.py (10-min repair)
- cycle.py (15-min OODA ledger)
- ooda_cycle.py (15-min agentnet)
- build_agent.py (6-hour expansion)
- learn_agent.py (nightly lessons)
- spectral_heartbeat.py (15-min network topology)

Propose EXACTLY ONE evolution action from these categories:
SPAWN: Create a new agent file (describe purpose + filename)
RETIRE: Mark an agent as redundant
UPGRADE: Change a workflow cadence or add a new data source
INTEGRATE: Wire two agents that should share data but don't

Format:
ACTION: [SPAWN/RETIRE/UPGRADE/INTEGRATE]
TARGET: [filename or workflow]
REPO: [which evez repo]
RATIONALE: [why, citing actual memory data]
IMPLEMENTATION: [3-sentence description of what to build]"""

    return call_claude(prompt)


def open_evolution_issue(plan_text):
    try:
        lines = plan_text.strip().split("\n") if plan_text else []
        action_line = next((l for l in lines if l.startswith("ACTION:")), "ACTION: EVOLVE")
        action = action_line.replace("ACTION:", "").strip()
        url = f"https://api.github.com/repos/{OWNER}/evez-autonomous-ledger/issues"
        r = requests.post(url, headers=HEADERS, json={
            "title": f"🧬 [EVOLUTION] {action}",
            "body": f"{plan_text}\n\n*🧬 Auto-generated by evolve.py every 12h | Human approval required.*",
            "labels": ["evolution", "autonomous-cognition"],
        }, timeout=15)
        return r.status_code in (200, 201)
    except Exception as e:
        print(f"  ⚠️  open_evolution_issue failed: {e}")
        return False


def main():
    try:
        print(f"\n🧬 EVEZ Evolution Engine — {now_iso()}")
        memory = get_memory_state()
        print(f"  Memory: {memory.get('total_records', 0)} records, {memory.get('lessons_count', 0)} lessons")

        plan = generate_evolution_plan(memory)
        if not plan:
            print("  ⚠️  No API key or memory — skipping evolution")
            return

        print(f"  Evolution plan:\n{plan[:400]}")
        opened = open_evolution_issue(plan)
        print(f"  {'✅' if opened else '❌'} Evolution issue opened on evez-autonomous-ledger")

        record = {
            "type": "evolution_proposal",
            "source": "evolution/evolve",
            "timestamp": now_iso(),
            "plan": plan,
            "hash": hashlib.sha256((plan or "").encode()).hexdigest()[:16],
        }
        content = base64.b64encode(json.dumps(record, indent=2).encode()).decode()
        ts = now_iso().replace(":", "-").replace(".", "-")
        try:
            requests.put(
                f"https://api.github.com/repos/{OWNER}/evez-autonomous-ledger/contents/DECISIONS/{ts}_evolution.json",
                headers=HEADERS,
                json={"message": f"🧬 evolution proposal @ {record['timestamp']}", "content": content},
                timeout=15,
            )
        except Exception as e:
            print(f"  ⚠️  Ledger write failed: {e}")
        print("  ✅ Evolution engine complete.")
    except Exception as e:
        print(f"  ❌ main() failed: {e}")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"❌ evolve.py fatal: {e}")
        exit(0)
