#!/usr/bin/env python3
"""
EVEZ Code Generator — Builder Module

Creates and commits files to repos via GitHub Contents API.
No cloning needed — everything goes through the REST API.
"""

import os
import json
import time
import base64
import datetime
import sys

try:
    import requests
except ImportError:
    print("ERROR: 'requests' not available.")
    sys.exit(0)

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
ORG = os.environ.get("REPO_OWNER", "EvezArt")
API = "https://api.github.com"
HEADERS = {
    "Authorization": f"Bearer {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
}
API_DELAY = 0.5


def utcnow():
    return datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")


def _api(method, url, **kwargs):
    time.sleep(API_DELAY)
    try:
        resp = getattr(requests, method)(url, headers=HEADERS, timeout=30, **kwargs)
        return resp
    except Exception as exc:
        print(f"  ⚠ API {method.upper()} {url}: {exc}")
        return None


def commit_file(repo, path, content, message, branch=None):
    """Create or update a file in a repo via GitHub Contents API."""
    url = f"{API}/repos/{ORG}/{repo}/contents/{path}"
    params = {}
    if branch:
        params["ref"] = branch

    # Check existing (need sha for updates)
    existing = _api("get", url, params=params)
    sha = None
    if existing and existing.status_code == 200:
        sha = existing.json().get("sha")

    payload = {
        "message": message,
        "content": base64.b64encode(content.encode()).decode(),
    }
    if sha:
        payload["sha"] = sha
    if branch:
        payload["branch"] = branch

    resp = _api("put", url, json=payload)
    if resp and resp.status_code in (200, 201):
        action = "updated" if sha else "created"
        print(f"    ✅ {action} {repo}/{path}")
        return True
    else:
        status = resp.status_code if resp else "no response"
        print(f"    ❌ Failed to commit {repo}/{path} (status={status})")
        return False


def generate_readme(repo_name, description=""):
    """Generate a basic README.md for a repo."""
    desc = description or f"Part of the {ORG} ecosystem."
    return f"""# {repo_name}

{desc}

## Overview

This repository is part of the [{ORG}](https://github.com/{ORG}) organization.

## Getting Started

```bash
git clone https://github.com/{ORG}/{repo_name}.git
cd {repo_name}
```

## Contributing

Contributions are welcome. Please open an issue or submit a pull request.

## License

See [LICENSE](LICENSE) for details.

---
*Auto-generated by EVEZ Autonomous Intelligence Core*
"""


def generate_gitignore(language=None):
    """Generate a .gitignore appropriate for the repo."""
    base = """# Dependencies
node_modules/
__pycache__/
*.pyc
.env
.env.local

# Build
dist/
build/
*.egg-info/

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Logs
*.log
"""
    if language and language.lower() == "python":
        base += """
# Python
venv/
.venv/
*.egg
.eggs/
.pytest_cache/
.mypy_cache/
"""
    elif language and language.lower() in ("javascript", "typescript"):
        base += """
# Node
node_modules/
.next/
.nuxt/
coverage/
"""
    return base


def generate_ci_workflow(repo_name, language=None):
    """Generate a basic CI workflow."""
    lang = (language or "").lower()

    if lang == "python":
        steps = """
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt || true
      - run: python -m pytest || echo 'No tests found'"""
    elif lang in ("javascript", "typescript"):
        steps = """
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci || npm install
      - run: npm test || echo 'No tests found'"""
    else:
        steps = """
      - run: echo 'CI check passed'"""

    return f"""name: CI
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4{steps}
"""


def generate_contributing():
    """Generate a CONTRIBUTING.md."""
    return f"""# Contributing to this project

Thank you for your interest in contributing!

## How to contribute

1. Fork the repository
2. Create a feature branch (`git checkout -b feat/my-feature`)
3. Commit your changes (`git commit -m 'add my feature'`)
4. Push to the branch (`git push origin feat/my-feature`)
5. Open a Pull Request

## Guidelines

- Keep changes focused and atomic
- Write clear commit messages
- Add tests for new functionality
- Follow existing code style

## Reporting Issues

Please use GitHub Issues to report bugs or request features.

---
*Part of the [{ORG}](https://github.com/{ORG}) ecosystem*
"""


def generate_code_of_conduct():
    """Generate a CODE_OF_CONDUCT.md based on Contributor Covenant."""
    return """# Code of Conduct

## Our Pledge

We pledge to make participation in our community a harassment-free experience
for everyone, regardless of age, body size, disability, ethnicity, gender
identity and expression, level of experience, nationality, personal appearance,
race, religion, or sexual identity and orientation.

## Our Standards

Examples of behavior that contributes to a positive environment:
- Using welcoming and inclusive language
- Being respectful of differing viewpoints
- Gracefully accepting constructive criticism
- Focusing on what is best for the community

## Enforcement

Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported to the project maintainers. All complaints will be reviewed and
investigated.

## Attribution

This Code of Conduct is adapted from the [Contributor Covenant](https://www.contributor-covenant.org/).
"""


def build_missing_files(repos_missing, repo_metadata=None):
    """Given analysis of missing files, generate and commit them.

    Args:
        repos_missing: list of {"repo": str, "missing": [str]}
        repo_metadata: optional dict of {repo_name: {"description": str, "language": str}}
    """
    if repo_metadata is None:
        repo_metadata = {}

    results = []
    for entry in repos_missing:
        repo = entry["repo"]
        meta = repo_metadata.get(repo, {})
        language = meta.get("language")
        description = meta.get("description", "")

        for missing_file in entry["missing"]:
            content = None
            path = None
            message = None

            if missing_file == "README.md":
                content = generate_readme(repo, description)
                path = "README.md"
                message = "docs: add README.md (auto-generated)"

            elif missing_file == ".gitignore":
                content = generate_gitignore(language)
                path = ".gitignore"
                message = "chore: add .gitignore (auto-generated)"

            elif missing_file == "CI workflows":
                content = generate_ci_workflow(repo, language)
                path = ".github/workflows/ci.yml"
                message = "ci: add basic CI workflow (auto-generated)"

            elif missing_file == "CONTRIBUTING.md":
                content = generate_contributing()
                path = "CONTRIBUTING.md"
                message = "docs: add CONTRIBUTING.md (auto-generated)"

            elif missing_file == "CODE_OF_CONDUCT.md":
                content = generate_code_of_conduct()
                path = "CODE_OF_CONDUCT.md"
                message = "docs: add CODE_OF_CONDUCT.md (auto-generated)"

            if content and path:
                ok = commit_file(repo, path, content, message)
                results.append({
                    "repo": repo,
                    "file": path,
                    "success": ok,
                    "timestamp": utcnow(),
                })

    return results


if __name__ == "__main__":
    # Standalone test
    print("Builder module loaded. Use build_missing_files() or commit_file() directly.")
