#!/usr/bin/env python3
"""
EVEZ Fix Agent — reads PENDING_HUMAN_APPROVAL fix-class plans from ledger
and generates GitHub PRs with patches for trivial fixes.
Runs after human approval signal is detected in review_queue.
"""
import os, json, base64, requests, hashlib, datetime

GH_TOKEN = os.environ.get("GITHUB_TOKEN", "")
OWNER = "EvezArt"
ANTHROPIC_KEY = os.environ.get("ANTHROPIC_API_KEY", "")

HEADERS = {
    "Authorization": f"Bearer {GH_TOKEN}",
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
}


def call_claude(prompt: str) -> str:
    if not ANTHROPIC_KEY:
        return ""
    import urllib.request
    body = json.dumps({
        "model": "claude-3-haiku-20240307",
        "max_tokens": 1024,
        "messages": [{"role": "user", "content": prompt}]
    }).encode()
    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=body,
        headers={
            "x-api-key": ANTHROPIC_KEY,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        }
    )
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read())["content"][0]["text"]


def get_repo_files(repo: str) -> list:
    url = f"https://api.github.com/repos/{OWNER}/{repo}/git/trees/HEAD?recursive=1"
    r = requests.get(url, headers=HEADERS)
    if r.status_code == 200:
        return [f["path"] for f in r.json().get("tree", []) if f["type"] == "blob"]
    return []


def create_fix_issue_comment(repo: str, issue_number: int, body: str):
    url = f"https://api.github.com/repos/{OWNER}/{repo}/issues/{issue_number}/comments"
    requests.post(url, headers=HEADERS, json={"body": body})


def generate_fix_summary(repo: str, issue_title: str, issue_body: str) -> str:
    files = get_repo_files(repo)
    file_list = "\n".join(files[:30])
    prompt = f"""You are the EVEZ autonomous fix agent. Given this GitHub issue:

REPO: {repo}
TITLE: {issue_title}
BODY: {issue_body}

KNOWN FILES:
{file_list}

Write a concise (3-5 sentence) autonomous action plan for fixing this issue.
Identify the most likely file(s) to change. Do NOT write code — only the plan.
End with: CONFIDENCE: HIGH/MEDIUM/LOW"""
    return call_claude(prompt)


def process_approved_plans():
    """Scan DECISIONS/ for approved fix plans and act on them."""
    url = f"https://api.github.com/repos/{OWNER}/evez-autonomous-ledger/contents/DECISIONS"
    r = requests.get(url, headers=HEADERS)
    if r.status_code != 200:
        print("No DECISIONS dir yet.")
        return

    files = r.json()
    processed = 0
    for f in files:
        if not f["name"].endswith(".json"):
            continue
        fr = requests.get(f["url"], headers=HEADERS)
        if fr.status_code != 200:
            continue
        plan = json.loads(base64.b64decode(fr.json()["content"]).decode())
        if plan.get("status") != "APPROVED" or plan.get("action_class") != "fix":
            continue

        print(f"  🔧 Processing approved fix: {plan['id']}")
        summary = generate_fix_summary(
            plan["repo"], plan["issue_title"],
            plan.get("issue_body", "")
        )
        if summary:
            create_fix_issue_comment(
                plan["repo"], plan["issue_number"],
                f"## 🤖 EVEZ Fix Agent — Autonomous Plan\n\n{summary}\n\n"
                f"*Generated by fix_agent.py | Chain: `{plan.get('chain_hash','?')[:12]}`*"
            )
            print(f"  ✅ Comment posted to {plan['repo']}#{plan['issue_number']}")
            processed += 1

    print(f"  → {processed} approved fixes actioned.")


if __name__ == "__main__":
    print(f"\n🔧 EVEZ Fix Agent — {datetime.datetime.utcnow().isoformat()}Z")
    process_approved_plans()
