#!/usr/bin/env bash
# ============================================================
# EVEZ-OS FREE API SETUP WIZARD
# Run once on KiloClaw or any machine running the EVEZ stack.
# All keys stored locally to ~/.evez-os/.env only.
# Nothing is sent anywhere. No network calls in this script.
# ============================================================
# Usage: bash evez_setup_wizard.sh
# ============================================================

set -euo pipefail

EVEZ_DIR="$HOME/.evez-os"
ENV_FILE="$EVEZ_DIR/.env"
mkdir -p "$EVEZ_DIR"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
BOLD='\033[1m'
RESET='\033[0m'

banner() {
  echo -e "${CYAN}"
  echo "╔══════════════════════════════════════════════════════════╗"
  echo "║          EVEZ-OS FREE API SETUP WIZARD v1.0             ║"
  echo "║          PID 335 | Guardian Charter | Cipher            ║"
  echo "╚══════════════════════════════════════════════════════════╝"
  echo -e "${RESET}"
}

section() { echo -e "\n${BOLD}${YELLOW}── $1 ──${RESET}"; }
info()    { echo -e "${CYAN}ℹ  $1${RESET}"; }
ok()      { echo -e "${GREEN}✓  $1${RESET}"; }
warn()    { echo -e "${RED}⚠  $1${RESET}"; }

ask_key() {
  local varname="$1"
  local label="$2"
  local url="$3"
  local notes="$4"

  echo ""
  echo -e "${BOLD}$label${RESET}"
  info "Free signup: $url"
  [ -n "$notes" ] && info "Notes: $notes"

  # Check if already set
  if [ -f "$ENV_FILE" ] && grep -q "^${varname}=" "$ENV_FILE" 2>/dev/null; then
    existing=$(grep "^${varname}=" "$ENV_FILE" | cut -d= -f2-)
    if [ -n "$existing" ] && [ "$existing" != '""' ]; then
      echo -e "${GREEN}  Already set: ${varname}=${existing:0:12}...${RESET}"
      read -r -p "  Replace? (y/N): " replace
      if [[ ! "$replace" =~ ^[Yy]$ ]]; then
        ok "Keeping existing $varname"
        return
      fi
    fi
  fi

  read -r -p "  Paste your $label (Enter to skip): " value
  if [ -n "$value" ]; then
    # Write or update in env file
    if grep -q "^${varname}=" "$ENV_FILE" 2>/dev/null; then
      sed -i "s|^${varname}=.*|${varname}=${value}|" "$ENV_FILE"
    else
      echo "${varname}=${value}" >> "$ENV_FILE"
    fi
    ok "$varname saved"
  else
    warn "Skipped $varname"
    # Write placeholder if not present
    if ! grep -q "^${varname}=" "$ENV_FILE" 2>/dev/null; then
      echo "# ${varname}=  # TODO: get free key at $url" >> "$ENV_FILE"
    fi
  fi
}

# ── START ─────────────────────────────────────────────────────────────────────

banner

echo -e "Output: ${BOLD}$ENV_FILE${RESET}"
echo "This file stays on your machine. Nothing is sent remotely."
echo ""
read -r -p "Press Enter to start, Ctrl+C to abort: "

# Initialize env file with header
if [ ! -f "$ENV_FILE" ]; then
  cat > "$ENV_FILE" << 'HEADER'
# EVEZ-OS Environment Variables
# Generated by evez_setup_wizard.sh
# Source this file: source ~/.evez-os/.env
# Or add to ~/.bashrc: source ~/.evez-os/.env
HEADER
fi

# ══════════════════════════════════════════════════════════════
section "1. FREE AI PROVIDERS (Required for n8n WF1-WF7)"
# ══════════════════════════════════════════════════════════════

ask_key "GROQ_API_KEY" \
  "Groq API Key (llama-3.3-70b FREE)" \
  "https://console.groq.com" \
  "14,400 requests/day free. No credit card. Used by WF1 + WF5 + WF6 + WF7."

ask_key "GEMINI_API_KEY" \
  "Google Gemini API Key (gemini-2.0-flash FREE)" \
  "https://aistudio.google.com/app/apikey" \
  "1,500 requests/day free. Google account required. Used by WF2 + WF5 + WF6 + WF7."

ask_key "OPENROUTER_API_KEY" \
  "OpenRouter API Key (llama:free, deepseek-r1:free, unlimited)" \
  "https://openrouter.ai/keys" \
  "Free tier: unlimited :free models. Used by WF3 + WF5 + WF7."

# ══════════════════════════════════════════════════════════════
section "2. BLOCKCHAIN / DeFi RPCs (Required for wallet stack)"
# ══════════════════════════════════════════════════════════════

ask_key "ALCHEMY_BASE_URL" \
  "Alchemy Base RPC URL (free tier)" \
  "https://dashboard.alchemy.com" \
  "Create app → select Base → copy HTTPS URL. 300M compute units/month free."

ask_key "ALCHEMY_ETH_URL" \
  "Alchemy Ethereum RPC URL (free tier)" \
  "https://dashboard.alchemy.com" \
  "Same account, create another app → Ethereum Mainnet."

ask_key "SOLANA_RPC_URL" \
  "Solana RPC URL" \
  "https://api.mainnet-beta.solana.com" \
  "Public free endpoint (rate-limited). Or use Helius: https://helius.dev (free tier 100k req/day)."

ask_key "MORPHO_MARKET_ID" \
  "Morpho Market ID (cbETH/USDC on Base)" \
  "https://app.morpho.org/base" \
  "Default: 0xb323495f7e4148be5643a4ea4a8221eef163e4bccfdedc2a6f4696baacbc86cc"

# ══════════════════════════════════════════════════════════════
section "3. GITHUB (Required for evez-autonomous-ledger commits)"
# ══════════════════════════════════════════════════════════════

ask_key "GITHUB_TOKEN" \
  "GitHub Personal Access Token" \
  "https://github.com/settings/tokens/new" \
  "Scopes needed: repo. Fine-grained PAT preferred. Used by n8n ledger writes + OKTOKLAW."

# ══════════════════════════════════════════════════════════════
section "4. CLOUDFLARE (Optional — CF Sentinel layer)"
# ══════════════════════════════════════════════════════════════

ask_key "CF_ACCOUNT_ID" \
  "Cloudflare Account ID (free)" \
  "https://dash.cloudflare.com → right sidebar" \
  "Free tier: Workers, Pages, D1, KV. No credit card required."

ask_key "CF_API_TOKEN" \
  "Cloudflare API Token" \
  "https://dash.cloudflare.com/profile/api-tokens" \
  "Create token → Edit Zone DNS + Workers Scripts permissions."

ask_key "CF_ZONE_ID" \
  "Cloudflare Zone ID (for your domain)" \
  "https://dash.cloudflare.com → your domain → Overview → right sidebar" \
  "Only needed if routing through a custom domain."

# ══════════════════════════════════════════════════════════════
section "5. SUPABASE (Optional — persistent DB layer)"
# ══════════════════════════════════════════════════════════════

ask_key "SUPABASE_URL" \
  "Supabase Project URL (free tier)" \
  "https://supabase.com/dashboard/projects" \
  "500MB DB, 1GB storage, 2GB bandwidth free. Create project → Settings → API."

ask_key "SUPABASE_ANON_KEY" \
  "Supabase Anon Key" \
  "https://supabase.com/dashboard → your project → Settings → API → anon public" \
  "Safe to use client-side. Pair with RLS policies."

# ══════════════════════════════════════════════════════════════
section "6. n8n (Required for workflow API dispatch)"
# ══════════════════════════════════════════════════════════════

ask_key "N8N_API_KEY" \
  "n8n API Key" \
  "https://evezos.app.n8n.cloud → Settings → API → Create API Key" \
  "Used for programmatic workflow triggers and status checks."

ask_key "N8N_BASE_URL" \
  "n8n Instance URL" \
  "https://evezos.app.n8n.cloud" \
  "Your n8n cloud URL. Default: https://evezos.app.n8n.cloud"

# ══════════════════════════════════════════════════════════════
section "7. TELEGRAM (Required for Morpheus alerts)"
# ══════════════════════════════════════════════════════════════

ask_key "TELEGRAM_BOT_TOKEN" \
  "Telegram Bot Token (@YVYZBOT)" \
  "https://t.me/BotFather → /newbot" \
  "If YVYZBOT token is already active, paste it here."

ask_key "TELEGRAM_CHAT_ID" \
  "Your Telegram Chat ID" \
  "https://t.me/userinfobot" \
  "Message @userinfobot on Telegram — it replies with your chat ID."

# ══════════════════════════════════════════════════════════════
section "8. ORACLE / INFRASTRUCTURE (Optional — bare metal layer)"
# ══════════════════════════════════════════════════════════════

ask_key "PHOENIX_BARE_METAL_IP" \
  "Oracle Cloud Phoenix Bare Metal IP" \
  "https://cloud.oracle.com → Compute → Instances" \
  "Your us-phoenix-1 instance IP. Free ARM tier: 4 OCPU, 24GB RAM."

# ══════════════════════════════════════════════════════════════
# WRITE SHELL LOADER
# ══════════════════════════════════════════════════════════════

LOADER_FILE="$EVEZ_DIR/load_env.sh"
cat > "$LOADER_FILE" << 'LOADER'
#!/usr/bin/env bash
# Source this to load all EVEZ-OS env vars into current shell
# Usage: source ~/.evez-os/load_env.sh

EVEZ_ENV="$HOME/.evez-os/.env"
if [ -f "$EVEZ_ENV" ]; then
  set -a
  # shellcheck source=/dev/null
  source "$EVEZ_ENV"
  set +a
  echo "✓ EVEZ-OS environment loaded"
else
  echo "⚠ No .env found at $EVEZ_ENV — run evez_setup_wizard.sh first"
fi
LOADER
chmod +x "$LOADER_FILE"

# ══════════════════════════════════════════════════════════════
# WRITE n8n ENV BLOCK (for paste into n8n Settings → Variables)
# ══════════════════════════════════════════════════════════════

N8N_BLOCK="$EVEZ_DIR/n8n_env_block.txt"
echo "# Copy-paste these into n8n Settings → Environment Variables" > "$N8N_BLOCK"
echo "# n8n Settings → (gear icon) → Environment Variables → + Add" >> "$N8N_BLOCK"
echo "" >> "$N8N_BLOCK"
for var in GROQ_API_KEY GEMINI_API_KEY OPENROUTER_API_KEY GITHUB_TOKEN \
           ALCHEMY_BASE_URL ALCHEMY_ETH_URL SOLANA_RPC_URL \
           MORPHO_MARKET_ID SUPABASE_URL SUPABASE_ANON_KEY \
           TELEGRAM_BOT_TOKEN TELEGRAM_CHAT_ID N8N_API_KEY; do
  val=$(grep "^${var}=" "$ENV_FILE" 2>/dev/null | cut -d= -f2- || echo "")
  if [ -n "$val" ]; then
    echo "${var}=${val}" >> "$N8N_BLOCK"
  fi
done

# ══════════════════════════════════════════════════════════════
# SUMMARY
# ══════════════════════════════════════════════════════════════

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════════════╗${RESET}"
echo -e "${CYAN}║                    SETUP COMPLETE                       ║${RESET}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════╝${RESET}"
echo ""

# Count configured keys
total=0; configured=0
for var in GROQ_API_KEY GEMINI_API_KEY OPENROUTER_API_KEY \
           ALCHEMY_BASE_URL ALCHEMY_ETH_URL SOLANA_RPC_URL \
           MORPHO_MARKET_ID GITHUB_TOKEN CF_ACCOUNT_ID CF_API_TOKEN \
           CF_ZONE_ID SUPABASE_URL SUPABASE_ANON_KEY N8N_API_KEY \
           N8N_BASE_URL TELEGRAM_BOT_TOKEN TELEGRAM_CHAT_ID PHOENIX_BARE_METAL_IP; do
  total=$((total+1))
  val=$(grep "^${var}=" "$ENV_FILE" 2>/dev/null | cut -d= -f2- || echo "")
  if [ -n "$val" ]; then
    ok "$var"
    configured=$((configured+1))
  else
    warn "$var — not set"
  fi
done

echo ""
echo -e "${BOLD}Configured: ${configured}/${total}${RESET}"
echo ""
echo -e "${BOLD}Files written:${RESET}"
echo "  $ENV_FILE          ← all keys (keep private)"
echo "  $LOADER_FILE       ← source this to load env"
echo "  $N8N_BLOCK         ← paste block for n8n UI"
echo ""
echo -e "${BOLD}To load env in any terminal session:${RESET}"
echo "  source ~/.evez-os/load_env.sh"
echo ""
echo -e "${BOLD}To add to ~/.bashrc (auto-load on login):${RESET}"
echo "  echo 'source ~/.evez-os/load_env.sh' >> ~/.bashrc"
echo ""
echo -e "${BOLD}To load wallet env for position monitor:${RESET}"
echo "  source ~/.evez-os/load_env.sh && cd evez-agentnet/wallet && npm run monitor"
echo ""
echo -e "${BOLD}For n8n — paste from:${RESET}"
echo "  cat ~/.evez-os/n8n_env_block.txt"
echo ""
echo -e "${CYAN}PID 335 | append-only | no edits | ever | witnessed: XyferViperZephyr${RESET}"
